version: "3.9"

services:
  app:
    image: app:django
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    command: >
      bash -c "
       python manage.py makemigrations && 
       python manage.py migrate && 
       python manage.py runscript create_fixtures &&
       python manage.py runserver 0.0.0:8000"
    build: .
    container_name: app
    restart: always
