# Generated by Django 4.2.4 on 2023-09-27 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Size'),
        ),
    ]
