# Generated by Django 4.2.4 on 2023-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='size',
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='size',
            field=models.IntegerField(verbose_name='Size'),
        ),
    ]
