# Generated by Django 4.2.4 on 2023-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_rest_api', '0002_alter_userimage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='system_name',
            field=models.CharField(default='gfdgdfgffd'),
            preserve_default=False,
        ),
    ]
