# Generated by Django 4.2.4 on 2023-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_rest_api', '0002_remove_userimage_size_alter_thumbnail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(upload_to='user_images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='user_images'),
        ),
    ]
