# Generated by Django 4.2.4 on 2023-10-12 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_rest_api', '0007_alter_thumbnail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Size'),
        ),
    ]
